- name: Install nginx
  package:
    name: nginx
    state: present
  notify: restart nginx

- name: Create nginx config directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Configure main nginx config
  template:
    src: "{{ nginx_template }}"
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: reload nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_remove_default_site
  notify: reload nginx

- name: Configure upstreams
  template:
    src: upstream.conf.j2
    dest: /etc/nginx/conf.d/upstream_{{ item.name }}.conf
  with_items: "{{ nginx_upstreams }}"
  notify: reload nginx

- name: Configure sites
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ item.name }}.conf
  with_items: "{{ nginx_sites }}"
  notify: reload nginx

- name: Enable sites
  file:
    src: /etc/nginx/sites-available/{{ item.name }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
    state: link
  with_items: "{{ nginx_sites }}"
  notify: reload nginx

- name: Ensure nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes